### ISSUE TITLE
Failed to submit large model

### ISSUE THREAD

**Issue by yingwaner** [facebookresearch/dynalab#102]
Hi, I use the command `dynalab-cli upload -n flores-ft-v3` to upload my submission but it failed.

```
Config file validated
Tarballing the project directory...
Uploading files to S3. For large submissions, the progress bar may hang a while even after uploading reaches 100%. Please do not kill it...
Uploading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8.14G/8.14G [14:40<00:00, 9.93MB/s]
Failed to submit model due to: 504 Server Error: Gateway Time-out for url: https://api.dynabench.org/models/upload/s3
You can inspect the prepared model submission locally at .dynalab_submissions/Jul-28-2021-15-17-21-flores-ft-v3.tar.gz
```

This submission is 263 (https://dynabench.org/models/263) and the status is failed (The model could not be deployed.)

I have checked the related issue, but none of them can solve my problem. My code is the latest version. Could you check it for me?

Thank you in advance.

**Comment by mazhiyi** [comment]
@yingwaner Thanks for flagging this. We are aware of the timeout error message, which turns out to be false positive in most cases (I've added more comments here https://github.com/facebookresearch/dynalab/issues/94), and I can confirm that the model was successfully uploaded. 

The failure to deployment was actually because of another issue on our backend (https://github.com/facebookresearch/dynalab/issues/101). 

I've resubmitted the deployment job for model 263. You should receive a new email regarding the deployment result soon.

**Comment by yingwaner** [comment]
thank you very much for your help! I have seen this submission successfully deployed.
